version: '3'

services:
  demospring-docker-compose-app-container:
    image: PoliticalSpeeches:latest
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - /data/demospring-docker-compose-app
    ports:
      -"8082:8080"